### ISSUE TITLE
zst compression not working

### ISSUE THREAD

**Issue by tim77** [flathub/org.kde.ark#3]
`zstandard` compression not working.

**How to reproduce:**

Try to made `zst` archive.

**Actual result:**

Error.

Other formats works fine.

**Comment by Siosm** [comment]
Can you try https://github.com/flathub/org.kde.ark/pull/4#issuecomment-649428306 and see if it fixes the issue?

**Comment by ElXreno** [comment]
@Siosm your PR fix this issue at least for me.

**Comment by tim77** [comment]
Still doesn't work. 😕 @Siosm some people said that zstd compression not works in Ark in Fedora 32 (RPM package). I'll try to ask help with testing them.

**Comment by tim77** [comment]
Nothing useful in terminal output when trying to create zst archive:
```
ark.libarchive: Failed to set compression method: Using external zstd program
```
