### ISSUE TITLE
Submitting reviews does not work

### ISSUE THREAD

**Issue by rajmondburgaj** [flathub/org.kde.ark#56]
Submitting reviews from Discover does not work.
It shows this message instead:

![image](https://user-images.githubusercontent.com/7545874/219880294-b4efae2f-6299-42d9-83ef-6a5ea71f560c.png)

**Comment by tsdgeos** [comment]
And why is this an ark problem?

**Comment by rajmondburgaj** [comment]
I am so sorry, completely missed it, will close the ticket.
